[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[secrets_scanning]
  omit_paths = [
    "dist/**/*",
    "package-lock.json",
    "package.json"
  ]
